github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true

image: jsii/superchain:1-buster-slim

tasks:
  - init: yarn install && ./scripts/foreach.sh yarn build

vscode:
  extensions:
    - dbaeumer.vscode-eslint
