github:
  prebuilds:
    pullRequestsFromForks: true
    addComment: true

image: jsii/superchain:1-buster-slim-node16

tasks:
  - init: yarn install && cd packages/aws-cdk-lib && NODE_OPTIONS=--max-old-space-size=8192 ../../scripts/buildup

vscode:
  extensions:
    - dbaeumer.vscode-eslint
