# See https://doc.mergify.io

pull_request_rules:
  - name: label core
    actions:
      label:
        add: [ contribution/core ]
    conditions:
      - author~=^(eladb|RomainMuller|garnaat|nija-at|skinny85|rix0rrr|NGL321|Jerry-AWS|MrArnoldPalmer|NetaNir|iliapolo|njlynch|ericzbeard|ccfife|fulghum|pkandasamy91|SoManyHs|uttarasridhar|otaviomacedo|BenChaimberg|madeline-k|BryanPan342)$
      - -label~="contribution/core"
  - name: automatic merge
    actions:
      comment:
        message: Thank you for contributing! Your pull request will be updated from master and then merged automatically (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      merge:
        strict: smart
        method: squash
        strict_method: merge
        commit_message: title+body
    conditions:
      - base!=release
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge|no-squash|two-approvers)
      - -merged
      - -closed
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      - "#changes-requested-reviews-by=0"
      - status-success~=AWS CodeBuild us-east-1
      - status-success=validate-pr
  - name: automatic merge (2+ approvers)
    actions:
      comment:
        message: Thank you for contributing! Your pull request will be automatically updated and merged (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      merge:
        strict: smart
        method: squash
        strict_method: merge
        commit_message: title+body
    conditions:
      - base!=release
      - -title~=(WIP|wip)
      - label~=two-approvers
      - -label~=(blocked|do-not-merge|no-squash)
      - -merged
      - -closed
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - "#approved-reviews-by>=2"
      - -approved-reviews-by~=author
      - "#changes-requested-reviews-by=0"
      - status-success~=AWS CodeBuild us-east-1
      - status-success=validate-pr
  - name: automatic merge (no-squash)
    actions:
      comment:
        message: Thank you for contributing! Your pull request will be automatically updated and merged without squashing (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      merge:
        strict: smart
        # Merge instead of squash
        method: merge
        strict_method: merge
        commit_message: title+body
    conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      # Only if no-squash is set
      - label~=no-squash
      - -merged
      - -closed
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      - "#changes-requested-reviews-by=0"
      - status-success~=AWS CodeBuild us-east-1
      - status-success=validate-pr
  - name: remove stale reviews
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: true
    conditions:
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - label!=contribution/core
      - base=master
      - -merged
      - -closed
  - name: if fails conventional commits
    actions:
      comment:
        message: Title does not follow the guidelines of [Conventional Commits](https://www.conventionalcommits.org). Please adjust title before merge.
    conditions:
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - status-failure=Semantic Pull Request
      - -merged
      - -closed
  - name: automatic merge of Dependabot PRs
    actions:
      comment:
        message: Thanks Dependabot!
      merge:
        # 'strict: false' disables Mergify keeping the branch up-to-date from master.
        # It's not necessary: Dependabot will do that itself.
        # It's not dangerous: GitHub branch protection settings prevent merging stale branches.
        strict: false
        method: squash
    conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
      - author~=dependabot
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - status-success~=AWS CodeBuild us-east-1
      - status-success=validate-pr
