# See https://doc.mergify.io
merge_queue:
  # Hopefully this gets Mergify to stop creating PRs just to test merges (it both messes with statistics and our automatic validations)
  max_parallel_checks: 1
queue_rules:
  - name: default-merge
    update_method: merge
    merge_method: merge
    conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      # Only if no-squash is set
      - label~=no-squash
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      # This is important! It makes the PR Linter work.
      - "#changes-requested-reviews-by=0"
      - check-success=validate-pr
      - check-success=build
    commit_message_template: |-
      {{ title }} (#{{ number }})
      {{ body }}

  - name: priority-squash
    update_method: merge
    merge_method: squash
    conditions:
      - base!=release
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge|no-squash)
      - label~=priority-pr
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      # This is important! It makes the PR Linter work.
      - "#changes-requested-reviews-by=0"
      - check-success=validate-pr
      - check-success=build
    commit_message_template: |-
      {{ title }} (#{{ number }})
      {{ body }}

  - name: default-squash
    update_method: merge
    merge_method: squash
    conditions:
      - base!=release
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge|no-squash|priority-pr)
      - -merged
      - -closed
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      # This is important! It makes the PR Linter work.
      - "#changes-requested-reviews-by=0"
      - check-success=validate-pr
      - check-success=build
    commit_message_template: |-
      {{ title }} (#{{ number }})
      {{ body }}

pull_request_rules:
  - name: label core
    actions:
      label:
        add: [contribution/core]
    conditions:
      - author=@aws/aws-cdk-team
      - -label~="contribution/core"
  - name: automatic merge
    actions:
      comment:
        message: Thank you for contributing! Your pull request will be updated from main and then merged automatically (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      queue:
        name: default-squash
    conditions:
      - base!=release
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge|no-squash|two-approvers|priority-pr)
      - -merged
      - -closed
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      # This is important! It makes the PR Linter work.
      - "#changes-requested-reviews-by=0"
      - check-success=validate-pr
      - check-success=build
  - name: automatic priority merge
    actions:
      comment:
        message: Thank you for contributing! Your pull request will be updated from main and then merged automatically (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      queue:
        name: priority-squash
    conditions:
      - base!=release
      - -title~=(WIP|wip)
      - label~=priority-pr
      - -label~=(blocked|do-not-merge|no-squash|two-approvers)
      - -merged
      - -closed
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      # This is important! It makes the PR Linter work.
      - "#changes-requested-reviews-by=0"
      - check-success=validate-pr
      - check-success=build
  - name: automatic merge (2+ approvers)
    actions:
      comment:
        message: Thank you for contributing! Your pull request will be automatically updated and merged (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      queue:
        name: default-squash
    conditions:
      - base!=release
      - -title~=(WIP|wip)
      - label~=two-approvers
      - -label~=(blocked|do-not-merge|no-squash)
      - -merged
      - -closed
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - "#approved-reviews-by>=2"
      - -approved-reviews-by~=author
      # This is important! It makes the PR Linter work.
      - "#changes-requested-reviews-by=0"
      - check-success=validate-pr
      - check-success=build
  - name: automatic merge (no-squash)
    actions:
      comment:
        message: Thank you for contributing! Your pull request will be automatically updated and merged without squashing (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      queue:
        name: default-merge
    conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      # Only if no-squash is set
      - label~=no-squash
      - -merged
      - -closed
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - "#approved-reviews-by>=1"
      - -approved-reviews-by~=author
      # This is important! It makes the PR Linter work.
      - "#changes-requested-reviews-by=0"
      - check-success=validate-pr
      - check-success=build
  - name: remove stale reviews
    actions:
      dismiss_reviews:
        approved: true
        changes_requested: true
    conditions:
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - label!=contribution/core
      - base=main
      - -merged
      - -closed
      - changes-requested-reviews-by!=aws-cdk-automation
  - name: if fails conventional commits
    actions:
      comment:
        message: Title does not follow the guidelines of [Conventional Commits](https://www.conventionalcommits.org). Please adjust title before merge.
    conditions:
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - status-failure=Semantic Pull Request
      - -merged
      - -closed
  - name: automatic merge of Dependabot PRs
    actions:
      comment:
        message: Thanks Dependabot!
      queue:
        name: default-squash
    conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
      - author~=dependabot
      - "#approved-reviews-by>=1"
      # This is important! It makes the PR Linter work.
      - "#changes-requested-reviews-by=0"
      - check-success=validate-pr
      - check-success=build
priority_rules:
  - name: priority for queue `default-merge`
    conditions:
      - -label~=(blocked|do-not-merge)
      - label~=no-squash
    priority: 2500
  - name: priority for queue `priority-squash`
    conditions:
      - -label~=(blocked|do-not-merge|no-squash)
      - label~=priority-pr
    priority: 2250
