language: python

# python is needed for the aws-s3-deployment-handler package
python:
  - "3.6"

branches:
  only:
    - master

env:
  - NODE_VERSION="8.11.3"

before_install:
  - nvm install $NODE_VERSION

cache:
  - npm
  - pip

install: ./install.sh
script:
  - ./build.sh
  - git update-index --refresh
  - git diff-index --exit-code --stat HEAD
  - untracked=$(git ls-files --others --exclude-standard) && echo "${untracked}" && test -z "${untracked}"
