version: 0.2

# This buildspec is intended to be run by CodePipeline builds.

phases:
  install:
    commands:
      # Install yarn if it wasn't already present in the image
      - yarn --version || npm -g install yarn
  pre_build:
    commands:
      - /bin/bash ./fetch-dotnet-snk.sh
  build:
    commands:
      - /bin/bash ./scripts/align-version.sh
      - /bin/bash ./build.sh
  post_build:
    commands:
      - "[ -f .BUILD_COMPLETED ] && /bin/bash ./pack.sh"
artifacts:
  files:
    - "**/*"
  base-directory: dist
