version: 0.2

phases:
  install:
    commands:
      - /bin/bash ./install.sh
  build:
    commands:
      - /bin/bash ./build.sh
  post_build:
    commands:
      - if [[ ! -f ".BUILD_COMPLETED" ]]; then exit 1
      - /bin/bash ./pack.sh
      - /bin/bash ./bundle-beta.sh
artifacts:
  files:
    - "**/*"
  base-directory: dist
