version: 0.2

# This buildspec is intended to be used by GitHub PR builds.

env:
  variables:
    # Globally allow node to use a lot of memory
    NODE_OPTIONS: --max-old-space-size=4096
    JSII_ROSETTA_MAX_WORKER_COUNT: 8

phases:
  install:
    commands:

      # baked in our image.
      # this also takes care of launching the docker daemon.
      - /root/ecr-proxy/start.sh

      # Install yarn if it wasn't already present in the image
      - yarn --version || npm -g install yarn
  build:
    commands:
      - /bin/bash ./build.sh --extract
      - /bin/bash ./scripts/transform.sh --extract
      - git diff-index --exit-code --ignore-space-at-eol --stat HEAD
