version: 0.2

# This buildspec is intended to be run by CodePipeline builds.

phases:
  install:
    commands:
      - /bin/bash ./install.sh
  pre_build:
    commands:
      - /bin/bash ./fetch-dotnet-snk.sh
  build:
    commands:
      - /bin/bash ./build.sh && git diff-index --exit-code --ignore-space-at-eol --stat HEAD
  post_build:
    commands:
      - "[ -f .BUILD_COMPLETED ] && /bin/bash ./pack.sh"
artifacts:
  files:
    - "**/*"
  base-directory: dist
