version: 0.2

# This buildspec is intended to be used by GitHub PR builds.

phases:
  install:
    commands:
      # Install yarn if it wasn't already present in the image
      - yarn --version || npm -g install yarn
  build:
    commands:
      - /bin/bash ./build.sh && git diff-index --exit-code --ignore-space-at-eol --stat HEAD
