version: 0.2

phases:
  install:
    commands:
      - /bin/bash ./install.sh
  pre_build:
    commands:
      - /bin/bash ./fetch-dotnet-snk.sh
  build:
    commands:
      - /bin/bash ./build.sh
  post_build:
    commands:
      - |
        if [ -f .BUILD_COMPLETED ]; then
          if [ -z \"${SKIP_PACK:-}\" ]; then
            /bin/bash ./pack.sh
          fi
        fi
artifacts:
  files:
    - "**/*"
  base-directory: dist
