version: 0.2

# This buildspec is intended to be used by GitHub PR builds.

phases:
  install:
    commands:

      # baked in our image.
      # this also takes care of launching the docker daemon.
      - /root/ecr-proxy/start.sh

      # Install yarn if it wasn't already present in the image
      - yarn --version || npm -g install yarn

      # Packing the mono-libraries (monocdk & aws-cdk-lib) can cause
      # memory errors. Increasing this value allows our build to more consistently succeed
      - (command -v sysctl || yum install -y procps-ng) && /sbin/sysctl -w vm.max_map_count=2251954
  build:
    commands:
      - /bin/bash ./build.sh --extract
      - /bin/bash ./scripts/transform.sh --extract
      - git diff-index --exit-code --ignore-space-at-eol --stat HEAD
