version: 0.2

phases:
  install:
    commands:
      - /bin/bash ./install.sh
  pre_build:
    commands:
      - /bin/bash ./fetch-dotnet-snk.sh
  build:
    commands:
      - /bin/bash ./build.sh
  post_build:
    commands:
      - "[ -f .BUILD_COMPLETED ] && [ -z "${SKIP_PACK:-}" ] && /bin/bash ./pack.sh"
artifacts:
  files:
    - "**/*"
  base-directory: dist
