name: 'Security Guardian'
description: 'Security Guardian for custom or granular guard rules'

inputs:
  data_directory:
    description: "Path to CloudFormation templates"
    required: true
  rule_set_path:
    description: "Path to a single .guard file locally"
    required: true
  show_summary:
    description: "cfn-guard summary output. Options are all, pass, fail, skip or none"
    required: false
    default: "fail"
  output_format:
    description: "cfn-guard output format. Options: json, yaml, single-line-summary"
    required: false
    default: "single-line-summary"

runs:
  using: node20
  main: dist/index.js

branding:
  icon: shield
  color: red
