name: 'Security Guardian'
description: 'Security Guardian for custom or granular guard rules'

inputs:
  base_sha:
    description: "Base commit id"
    required: false
  head_sha:
    description: "Current changes commit id"
    required: false
  rule_set_path:
    description: "Path to a single .guard file locally"
    required: true
  show_summary:
    description: "cfn-guard summary output. Options are all, pass, fail, skip or none"
    required: false
    default: "fail"
  output_format:
    description: "cfn-guard output format. Options: json, yaml, single-line-summary"
    required: false
    default: "single-line-summary"
  enable_intrinsic_scanner:
    description: "Enable intrinsic scanner for resolved CloudFormation values"
    required: false
    default: "false"

runs:
  using: node20
  main: dist/index.js

branding:
  icon: shield
  color: red
