name: Bug Report
description: Report a bug
title: "(module name): short issue description"
labels: [bug, needs-triage]
body:
  - type: textarea
    id: problem
    attributes:
      label: What is the problem?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: |
        Minimal amount of code that causes the bug (if possible) or a reference.

        The code sample should be an SSCCE. See http://sscce.org/ for details.
        In short, provide a code sample that we can copy/paste, run and reproduce.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: |
        What were you trying to achieve by performing the steps above?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: What actually happened?
      description: |
        What is the unexpected behavior you were seeing? If you got an error, paste it here.
    validations:
      required: true

  - type: input
    id: cdk-version
    attributes:
      label: CDK CLI Version
      description: Output of `cdk version`
    validations:
      required: true

  - type: input
    id: framework-version
    attributes:
      label: Framework Version
    validations:
      required: false

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: OS
    validations:
      required: true

  - type: dropdown
    id: language
    attributes:
      label: Language
      multiple: true
      options:
        - Typescript
        - Python
        - .NET
        - Java
        - Go
    validations:
      required: true

  - type: input
    id: language-version
    attributes:
      label: Language Version
      description: E.g. TypeScript (3.8.3) | Java (8) | Python (3.7.3)
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: Other information
      description: |
        e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---

        This is :bug: Bug Report
