name: Documentation Issue
description: Issue in the reference documentation or developer guide
title: "(module name): short issue description"
labels: [feature-request, documentation, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        Developer guide? Raise issue/pr here: https://github.com/awsdocs/aws-cdk-guide

        Want to help? Submit a pull request here: https://github.com/aws/aws-cdk

  - type: input
    id: doc-link
    attributes:
      label: link to reference doc page
    validations:
      required: false

  - type: textarea
    id: issue
    attributes:
      label: Describe your issue?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

        This is a 📕 documentation issue
