name: General Issue
description: Create a new issue
title: "(module name): short issue description"
labels: [needs-triage, guidance]
body:
  - type: markdown
    attributes:
      value: |
        If there is an issue regarding developer guide, please create an issue [here](https://github.com/awsdocs/aws-cdk-guide/issues).

  - type: input
    id: issue
    attributes:
      label: General Issue
      description: |
        For support questions, please first reference our [documentation](https://docs.aws.amazon.com/cdk/api/latest), then use [Stackoverflow](https://stackoverflow.com/questions/tagged/aws-cdk). This repository's issues are intended for feature requests and bug reports.
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: The Question
      description: |
        Ask your question here. Include any details relevant. Make sure you are not falling prey to the [X/Y problem](http://xyproblem.info)!
    validations:
      required: true

  - type: input
    id: cdk-version
    attributes:
      label: CDK CLI Version
      description: Output of `cdk version`
    validations:
      required: true

  - type: input
    id: framework-version
    attributes:
      label: Framework Version
    validations:
      required: false

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
    validations:
      required: false

  - type: input
    id: operating-system
    attributes:
      label: OS
    validations:
      required: false

  - type: dropdown
    id: language
    attributes:
      label: Language
      multiple: true
      options:
        - Typescript
        - Python
        - .NET
        - Java
        - Go
    validations:
      required: true

  - type: input
    id: language-version
    attributes:
      label: Language Version
      description: E.g. TypeScript (3.8.3) | Java (8) | Python (3.7.3)
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: Other information
      description: |
        e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. associated pull-request, stackoverflow, slack, etc
    validations:
      required: false
