name: Tracking Issue
description: Add a module tracking issue (internal use only)
title: "Tracking: [service]"
labels: [management/tracking]
body:
  - type: markdown
    attributes:
      value: |
        Add your +1 👍  to help us prioritize high-level constructs for this service

  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: |
        Summary of the service (leverage the service’s product page for the text) and a link to the relevant AWS Docs. This should be the same text that we put at the top of the package’s README.md.
    validations:
      required: true

  - type: input
    id: cdk-api-docs-link
    attributes:
      label: Link to the service’s CDK Construct Library API reference page.
    validations:
      required: true

  - type: dropdown
    id: maturity
    attributes:
      label:  "Maturity: CloudFormation Resources Only"
      description: |
        See the [AWS Construct Library Module Lifecycle doc](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0107-construct-library-module-lifecycle.md) for more information about maturity levels.
      options:
        - CloudFormation Resources Only
        - Experimental
        - Developer Preview
        - Stable
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation
      description: |
        Checklist of use cases, constructs, features (such as grant methods) that will ship in this package. This is not required until the issue is added to the public roadmap.
    validations:
      required: true

  - type: textarea
    id: issue-list
    attributes:
      label: Issue list
      description: |
        Checklist of links to feature requests, bugs, and PRs that are in scope for GA release of this module (not required until the issues is added to the public roadmap).
      value: |
          - [ ]
          - [ ]
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Labels to add:
        - package/[name] (create new labels if they don’t already exist)
        - needs-design (if cfn-only)
        - management/roadmap (when added to the roadmap)
        - in-progress (when added to “working on it” column of the roadmap)

  - type: markdown
    attributes:
      value: |
        ---

        This is a 📊 Tracking Issue
