export * from './policy-document';
export * from './policy-statement';
export * from './managed-policy';
export * from './role';
export * from './policy';
export * from './user';
export * from './group';
export * from './lazy-role';
export * from './principals';
export * from './identity-base';
export * from './grant';
export * from './unknown-principal';
export * from './oidc-provider';
export * from './permissions-boundary';
export * from './saml-provider';
export * from './access-key';
export * from './utils';

// AWS::IAM CloudFormation Resources:
export * from './iam.generated';
