#!/bin/bash
set -euo pipefail
scriptdir=$(cd $(dirname $0) && pwd)

echo "************************************************************"
echo " builddown usage:"
echo " - execute 'builddown --resume' to resume after failure"
echo " - execute 'builddown' to restart the build from the start"
echo ""
echo " for advanced usage, see ${scriptdir}/foreach.sh"
echo "************************************************************"

if [ "$#" -eq 0 ]; then
  ${scriptdir}/foreach.sh --reset --down yarn build
else
  if [ "$1" != "--resume" ]; then
    echo "Unknown option: $1"
    exit 1
  fi
  ${scriptdir}/foreach.sh --down yarn build
fi

echo "************************************************************"
echo "builddown done"
echo "************************************************************"
