#!/bin/bash
set -euo pipefail
scriptdir=$(cd $(dirname $0) && pwd)

echo "************************************************************"
echo " buildup usage:"
echo " - execute 'buildup' again to resume after failure"
echo " - execute 'buildup --restart' to restart"
echo ""
echo " for advanced usage, see ${scriptdir}/foreach.sh"
echo "************************************************************"

if [ "${1:-}" == "--restart" ] || [ "${1:-}" == "--reset" ]; then
  ${scriptdir}/foreach.sh --reset
fi


${scriptdir}/foreach.sh --up yarn build
