#!/bin/bash
# For people that want a base VSCode setup (with useful launchers etc)
# But without checking in a .vscode directory by default: there are
# people who definitely do not want it checked in.
set -eu
scriptdir=$(cd $(dirname $0) && pwd)

mkdir -p ${scriptdir}/../.vscode
cp ${scriptdir}/default.vscode/* ${scriptdir}/../.vscode

