#!/bin/bash
# Collects the directories of all jsii packages and the names of all non-jsii packages into 2 files
set -eu
scriptdir=$(cd $(dirname $0) && pwd)

jsii_file="$1"
nonjsii_file="$2"

$scriptdir/nx-query.mts 'jsii()' > "$jsii_file"
$scriptdir/nx-query.mts --names '~jsii()' > "$nonjsii_file"
