#!/usr/bin/env -S node --experimental-strip-types
import { execFileSync } from 'child_process';

interface NxGraph {
  graph: {
    nodes: Record<string, {
      data: {
        root: string;
      },
    }>;
    dependencies: Record<string, {
      source: string;
      target: string;
      type: string;
    }[]>;
  }
}

function main() {
  const output = JSON.parse(execFileSync('npx', ['nx', 'graph', '--print'], { encoding: 'utf-8' }));

  const nodes = Object.keys(output.graph.nodes);
  const directories = Object.fromEntries(nodes.map(node => [node, output.graph.nodes[node].data.root]));
  const graph: Record<string, []> = Object.fromEntries(nodes.map(node => [node, []]));

  for (const nodeEdges of Object.values(output.graph.dependencies ?? {})) {
    for (const edge of nodeEdges) {
    }
  }

  console.log(graph);
}

main();