import * as integ from '@aws-cdk/integ-tests-alpha';
import * as cdk from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as agentcore from '../../../lib';

const app = new cdk.App();
const stack = new cdk.Stack(app, 'cdk-agentcore-gateway-auto-generated-name');

// Create Gateway without specifying name (auto-generated)
const gateway = new agentcore.Gateway(stack, 'Gateway', {
});

// Create Lambda function for target
const fn = new lambda.Function(stack, 'TestFunction', {
  runtime: lambda.Runtime.NODEJS_22_X,
  handler: 'index.handler',
  code: lambda.Code.fromInline('exports.handler = async () => ({ statusCode: 200 });'),
});

const toolSchema = agentcore.ToolSchema.fromInline([{
  name: 'test_tool',
  description: 'A test tool',
  inputSchema: {
    type: agentcore.SchemaDefinitionType.OBJECT,
    properties: {},
  },
}]);

// Create GatewayTarget without specifying name (auto-generated)
gateway.addLambdaTarget('Target', {
  lambdaFunction: fn,
  toolSchema: toolSchema,
});

new integ.IntegTest(app, 'GatewayAutoGeneratedName', {
  testCases: [stack],
});
