export * from './instance';
export * from './alias-target-instance';
export * from './cname-instance';
export * from './ip-instance';
export * from './non-ip-instance';
export * from './namespace';
export * from './http-namespace';
export * from './private-dns-namespace';
export * from './public-dns-namespace';
export * from './service';
// AWS::ServiceDiscovery CloudFormation Resources:
export * from './servicediscovery.generated';
