# Automatically approve PRs made by Dependabot
#
# Written to look at the original author of the PR (instead of the current
# actor) in order to be able to backresolve existing PRs using this action (by
# mass labeling them). Leads to slightly unnecessary spammage of aprovals in a
# PR...
#
# Only does approvals! A different GitHub Action takes care of merging.
name: Auto-approve Dependabot
on:
  pull_request:
    types:
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@7782c7e2bdf62b4d79bdcded8332808fd2f179cd
      if: github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot-preview[bot]'
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
