# Automatically approve PRs that merge master forward to v2-main
#
# Only does approvals! mergify takes care of the actual merge.
name: Auto-approve automated PRs around CDK v2
on:
  pull_request:
    types:
      - labeled
      - opened
      - ready_for_review
      - reopened
      - synchronize
      - unlabeled
      - unlocked

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/auto-approve-action@v2.0.0
      if: >
        github.event.pull_request.user.login == 'aws-cdk-automation'
        && github.event.pull_request.base.ref == 'v2-main'
        && contains(github.event.pull_request.labels.*.name, 'pr/auto-approve')
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
