
name: Check Run Logger

on:
  check_run:
    types: [completed]

jobs:
  log-check-run:
    runs-on: ubuntu-latest

    steps:
      - name: Log check run event details
        run: |
          echo "Check Run ID: ${{ github.event.check_run.id }}"
          echo "Status: ${{ github.event.check_run.status }}"
          echo "Conclusion: ${{ github.event.check_run.conclusion }}"
          echo "URL: ${{ github.event.check_run.url }}"
          echo "Head Branch: ${{ github.event.check_run.head_branch }}"
          echo "Head SHA: ${{ github.event.check_run.head_sha }}"
          echo "Repository: ${{ github.event.repository.full_name }}"
          echo "Sender: ${{ github.event.sender.login }}"
          echo "Created At: ${{ github.event.check_run.created_at }}"
          echo "Updated At: ${{ github.event.check_run.updated_at }}"
          echo "Pull Requests: ${{ toJson(github.event.check_run.pull_requests) }}"
