
name: Check Suite Logger

on:
  check_suite:
    types: [completed]

jobs:
  log-check-suite:
    runs-on: ubuntu-latest

    steps:
      - name: Log check suite event details
        run: |
          echo "Check Suite ID: ${{ github.event.check_suite.id }}"
          echo "Status: ${{ github.event.check_suite.status }}"
          echo "Conclusion: ${{ github.event.check_suite.conclusion }}"
          echo "URL: ${{ github.event.check_suite.url }}"
          echo "Head Branch: ${{ github.event.check_suite.head_branch }}"
          echo "Head SHA: ${{ github.event.check_suite.head_sha }}"
          echo "Repository: ${{ github.event.repository.full_name }}"
          echo "Sender: ${{ github.event.sender.login }}"
          echo "Created At: ${{ github.event.check_suite.created_at }}"
          echo "Updated At: ${{ github.event.check_suite.updated_at }}"
          echo "Pull Requests: ${{ toJson(github.event.check_suite.pull_requests) }}"