name: Codebuild PR Deployment Integration Test

permissions:
  id-token: write

on:
  workflow_dispatch: {}
  merge_group: {}
  pull_request:
    branches:
      - main
    paths:
      - '**.js.snapshot**'

# For every PR, cancel any previous builds in progress
# ... but for all other builds we keep them running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: codebuild-aws-cdk-github-actions-deployment-integ-runner-${{ github.run_id }}-${{ github.run_attempt }}
    environment: deployment-integ-test

    env:
      PR_BUILD: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: git debug
        run: |
          git log -n 5
          git status
          git branch
          echo 'Base SHA' ${{ github.event.pull_request.base.sha }}
          echo 'Head SHA' ${{ github.event.pull_request.head.sha }}
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --name-only
      
      - name: Assume Atmosphere Role
        id: creds
        run: |
          # Assume role and capture the JSON output
          CREDS=$(aws sts assume-role \
          --role-arn ${{ vars.CDK_ATMOSPHERE_OIDC_ROLE }} \
          --role-session-name run-tests@aws-cdk-deployment-integ)

          # Parse the JSON output and set environment variables
          echo "AWS_ACCESS_KEY_ID=$(echo $CREDS | jq -r '.Credentials.AccessKeyId')" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=$(echo $CREDS | jq -r '.Credentials.SecretAccessKey')" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=$(echo $CREDS | jq -r '.Credentials.SessionToken')" >> $GITHUB_ENV

      - name: Confirm that the atmosphere role has been assumed.
        run: |
          aws sts get-caller-identity   

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Load Docker images
        id: docker-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.docker-images.tar
          key: docker-cache-${{ runner.os }}

      - name: Restore Docker images
        if: ${{ steps.docker-cache.outputs.cache-hit }}
        run: docker image load --input ~/.docker-images.tar

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.s3buildcache
          key: s3buildcache-${{ runner.os }}

      - name: Configure system settings
        run: |
          (command -v sysctl || sudo apt-get update && sudo apt-get install -y procps) && \
          sudo sysctl -w vm.max_map_count=2251954

      - name: Build
        run: /bin/bash ./build.sh --ci --skip-test --skip-prereqs --skip-compat

      - name: Run deployment integration tests
        run: node tools/@aws-cdk/deployment-integ/bin/deployment-integ.js
        env:
          CDK_ATMOSPHERE_ENDPOINT: ${{ vars.CDK_ATMOSPHERE_ENDPOINT }}
          CDK_ATMOSPHERE_POOL: ${{ vars.CDK_ATMOSPHERE_POOL}}
          BASE_COMMIT: ${{ github.event.pull_request.base.sha }}
          HEAD_COMMIT: ${{ github.event.pull_request.head.sha }}
          

      - name: Export Docker images
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: docker image save --output ~/.docker-images.tar $(docker image list --format '{{ if ne .Repository "<none>" }}{{ .Repository }}{{ if ne .Tag "<none>" }}:{{ .Tag }}{{ end }}{{ else }}{{ .ID }}{{ end }}')

      - name: Cache Docker images
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.docker-images.tar
          key: docker-cache-${{ runner.os }}
