name: "Custom resources checklist"
on:
  pull_request:
    types: [ opened ]

jobs:
  checklist_job:
    runs-on: ubuntu-latest
    name: Creates a checklist for PRs that contain changes to custom resources
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Dynamic checklist action
        uses: vishalsinha21/dynamic-checklist@v1
        with:
          mappingFile: './.github/workflows/cr-mapping.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

