name: "Set Issue Label and Assignee"
on:
 issues:
    types: [opened, edited]
 pull_request:
    types: [opened, edited]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@f229cda
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          title-or-body: 'title'
          parameters: >
           [
           {"keywords":["cli","command line"],"labels":["package/tools"],"assignees":["shivlaks"]},
           {"keywords":["alexa-ask","alexa ask"],"labels":["@aws-cdk/alexa-ask"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["app-delivery","app delivery"],"labels":["@aws-cdk/app-delivery"],"assignees":["skinny85"]},
           {"keywords":["assert"],"labels":["@aws-cdk/assert"],"assignees":["eladb"]},
           {"keywords":["assets"],"labels":["@aws-cdk/assets"],"assignees":["eladb"]},
           {"keywords":["accessanalyzer","access analyzer"],"labels":["@aws-cdk/aws-accessanalyzer"],"assignees":["rix0rrr"]},
           {"keywords":["amazonmq","amazon mq"],"labels":["@aws-cdk/aws-amazonmq"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["amplify"],"labels":["@aws-cdk/aws-amplify"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["apigateway","api gateway"],"labels":["@aws-cdk/aws-apigateway"],"assignees":["nija-at"]},
           {"keywords":["applicationautoscaling","application autoscaling"],"labels":["@aws-cdk/aws-applicationautoscaling"],"assignees":["NetaNir"]},
           {"keywords":["appmesh","app mesh"],"labels":["@aws-cdk/aws-appmesh"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["appstream","app stream"],"labels":["@aws-cdk/aws-appstream"],"assignees":["NetaNir"]},
           {"keywords":["appsync","app sync"],"labels":["@aws-cdk/aws-appsync"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["athena"],"labels":["@aws-cdk/aws-athena"],"assignees":["iliapolo"]},
           {"keywords":["autoscaling"],"labels":["@aws-cdk/aws-autoscaling"],"assignees":["NetaNir"]},
           {"keywords":["autoscaling-api","autoscaling api"],"labels":["@aws-cdk/aws-autoscaling-api"],"assignees":["NetaNir"]},
           {"keywords":["autoscaling-common","autoscaling common"],"labels":["@aws-cdk/aws-autoscaling-common"],"assignees":["NetaNir"]},
           {"keywords":["autoscaling-hooktargets","autoscaling hooktargets"],"labels":["@aws-cdk/aws-autoscaling-hooktargets"],"assignees":["NetaNir"]},
           {"keywords":["autoscalingplans","autoscaling plans"],"labels":["@aws-cdk/aws-autoscalingplans"],"assignees":["NetaNir"]},
           {"keywords":["backup"],"labels":["@aws-cdk/aws-backup"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["batch"],"labels":["@aws-cdk/aws-batch"],"assignees":["iliapolo"]},
           {"keywords":["budgets"],"labels":["@aws-cdk/aws-budgets"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["certificatemanager","certificate manager"],"labels":["@aws-cdk/aws-certificatemanager"],"assignees":["skinny85"]},
           {"keywords":["cloud9","cloud 9"],"labels":["@aws-cdk/aws-cloud9"],"assignees":["skinny85"]},
           {"keywords":["cloudformation"],"labels":["@aws-cdk/aws-cloudformation"],"assignees":["eladb"]},
           {"keywords":["cloudfront","cloud front"],"labels":["@aws-cdk/aws-cloudfront"],"assignees":["iliapolo"]},
           {"keywords":["cloudtrail","cloud trail"],"labels":["@aws-cdk/aws-cloudtrail"],"assignees":["rix0rrr"]},
           {"keywords":["cloudwatch","cloud watch"],"labels":["@aws-cdk/aws-cloudwatch"],"assignees":["rix0rrr"]},
           {"keywords":["cloudwatch-actions","cloudwatch actions"],"labels":["@aws-cdk/aws-cloudwatch-actions"],"assignees":["rix0rrr"]},
           {"keywords":["codebuild","code build"],"labels":["@aws-cdk/aws-codebuild"],"assignees":["skinny85"]},
           {"keywords":["codecommit","code commit"],"labels":["@aws-cdk/aws-codecommit"],"assignees":["skinny85"]},
           {"keywords":["codedeploy","code deploy"],"labels":["@aws-cdk/aws-codedeploy"],"assignees":["skinny85"]},
           {"keywords":["codepipeline","code pipeline"],"labels":["@aws-cdk/aws-codepipeline"],"assignees":["skinny85"]},
           {"keywords":["codepipeline-actions","codepipeline actions"],"labels":["@aws-cdk/aws-codepipeline-actions"],"assignees":["skinny85"]},
           {"keywords":["codestar"],"labels":["@aws-cdk/aws-codestar"],"assignees":["skinny85"]},
           {"keywords":["codestarconnections","codestar connections"],"labels":["@aws-cdk/aws-codestarconnections"],"assignees":["skinny85"]},
           {"keywords":["codestarnotifications","codestar notifications"],"labels":["@aws-cdk/aws-codestarnotifications"],"assignees":["skinny85"]},
           {"keywords":["cognito"],"labels":["@aws-cdk/aws-cognito"],"assignees":["nija-at"]},
           {"keywords":["config"],"labels":["@aws-cdk/aws-config"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["datapipeline","data pipeline"],"labels":["@aws-cdk/aws-datapipeline"],"assignees":["iliapolo"]},
           {"keywords":["dax"],"labels":["@aws-cdk/aws-dax"],"assignees":["RomainMuller"]},
           {"keywords":["directoryservice","directory service"],"labels":["@aws-cdk/aws-directoryservice"],"assignees":["NetaNir"]},
           {"keywords":["dlm"],"labels":["@aws-cdk/aws-dlm"],"assignees":["nija-at"]},
           {"keywords":["dms"],"labels":["@aws-cdk/aws-dms"],"assignees":["nija-at"]},
           {"keywords":["docdb","doc db"],"labels":["@aws-cdk/aws-docdb"],"assignees":["iliapolo"]},
           {"keywords":["dynamodb","dynamo db"],"labels":["@aws-cdk/aws-dynamodb"],"assignees":["RomainMuller"]},
           {"keywords":["dynamodb-global","dynamodb global"],"labels":["@aws-cdk/aws-dynamodb-global"],"assignees":["RomainMuller"]},
           {"keywords":["ec2"],"labels":["@aws-cdk/aws-ec2"],"assignees":["rix0rrr"]},
           {"keywords":["ecr"],"labels":["@aws-cdk/aws-ecr"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["ecr-assets","ecr assets"],"labels":["@aws-cdk/aws-ecr-assets"],"assignees":["eladb"]},
           {"keywords":["ecs"],"labels":["@aws-cdk/aws-ecs"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["ecs-patterns","ecs patterns"],"labels":["@aws-cdk/aws-ecs-patterns"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["efs"],"labels":["@aws-cdk/aws-efs"],"assignees":["rix0rrr"]},
           {"keywords":["eks"],"labels":["@aws-cdk/aws-eks"],"assignees":["eladb"]},
           {"keywords":["elasticache","elastic cache"],"labels":["@aws-cdk/aws-elasticache"],"assignees":["iliapolo"]},
           {"keywords":["elasticbeanstalk","beanstalk"],"labels":["@aws-cdk/aws-elasticbeanstalk"],"assignees":["skinny85"]},
           {"keywords":["elasticloadbalancing","elb"],"labels":["@aws-cdk/aws-elasticloadbalancing"],"assignees":["rix0rrr"]},
           {"keywords":["elasticloadbalancingv2","elbv2"],"labels":["@aws-cdk/aws-elasticloadbalancingv2"],"assignees":["rix0rrr"]},
           {"keywords":["elasticloadbalancingv2-targets","elasticloadbalancingv2 targets","elbv2 targets"],"labels":["@aws-cdk/aws-elasticloadbalancingv2-targets"],"assignees":["rix0rrr"]},
           {"keywords":["elasticsearch","elastic search"],"labels":["@aws-cdk/aws-elasticsearch"],"assignees":["iliapolo"]},
           {"keywords":["emr"],"labels":["@aws-cdk/aws-emr"],"assignees":["iliapolo"]},
           {"keywords":["events","eventbridge","cloudwatch events"],"labels":["@aws-cdk/aws-events"],"assignees":["rix0rrr"]},
           {"keywords":["events-targets","events targets"],"labels":["@aws-cdk/aws-events-targets"],"assignees":["rix0rrr"]},
           {"keywords":["fsx"],"labels":["@aws-cdk/aws-fsx"],"assignees":["rix0rrr"]},
           {"keywords":["gamelift","game lift"],"labels":["@aws-cdk/aws-gamelift"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["glue"],"labels":["@aws-cdk/aws-glue"],"assignees":["iliapolo"]},
           {"keywords":["greengrass","green grass"],"labels":["@aws-cdk/aws-greengrass"],"assignees":["shivlaks"]},
           {"keywords":["guardduty","guard duty"],"labels":["@aws-cdk/aws-guardduty"],"assignees":["rix0rrr"]},
           {"keywords":["iam"],"labels":["@aws-cdk/aws-iam"],"assignees":["rix0rrr"]},
           {"keywords":["inspector"],"labels":["@aws-cdk/aws-inspector"],"assignees":["rix0rrr"]},
           {"keywords":["iot"],"labels":["@aws-cdk/aws-iot"],"assignees":["shivlaks"]},
           {"keywords":["iot1click","iot 1 click"],"labels":["@aws-cdk/aws-iot1click"],"assignees":["shivlaks"]},
           {"keywords":["iotanalytics","iot analytics"],"labels":["@aws-cdk/aws-iotanalytics"],"assignees":["shivlaks"]},
           {"keywords":["iotevents","iot events"],"labels":["@aws-cdk/aws-iotevents"],"assignees":["shivlaks"]},
           {"keywords":["iotthingsgraph","iot things graph"],"labels":["@aws-cdk/aws-iotthingsgraph"],"assignees":["shivlaks"]},
           {"keywords":["kinesis"],"labels":["@aws-cdk/aws-kinesis"],"assignees":["iliapolo"]},
           {"keywords":["kinesisanalytics","kinesis analytics"],"labels":["@aws-cdk/aws-kinesisanalytics"],"assignees":["iliapolo"]},
           {"keywords":["kinesisfirehose","firehose"],"labels":["@aws-cdk/aws-kinesisfirehose"],"assignees":["iliapolo"]},
           {"keywords":["kms"],"labels":["@aws-cdk/aws-kms"],"assignees":["skinny85"]},
           {"keywords":["lakeformation","lake formation"],"labels":["@aws-cdk/aws-lakeformation"],"assignees":["iliapolo"]},
           {"keywords":["lambda"],"labels":["@aws-cdk/aws-lambda"],"assignees":["nija-at"]},
           {"keywords":["lambda-event-sources","lambda event sources"],"labels":["@aws-cdk/aws-lambda-event-sources"],"assignees":["nija-at"]},
           {"keywords":["logs"],"labels":["@aws-cdk/aws-logs"],"assignees":["rix0rrr"]},
           {"keywords":["logs-destinations","logs destinations"],"labels":["@aws-cdk/aws-logs-destinations"],"assignees":["rix0rrr"]},
           {"keywords":["managedblockchain","managed blockchain"],"labels":["@aws-cdk/aws-managedblockchain"],"assignees":["shivlaks"]},
           {"keywords":["mediaconvert","media convert"],"labels":["@aws-cdk/aws-mediaconvert"],"assignees":["rix0rrr"]},
           {"keywords":["medialive","media live"],"labels":["@aws-cdk/aws-medialive"],"assignees":["rix0rrr"]},
           {"keywords":["mediastore","media store"],"labels":["@aws-cdk/aws-mediastore"],"assignees":["rix0rrr"]},
           {"keywords":["msk"],"labels":["@aws-cdk/aws-msk"],"assignees":["iliapolo"]},
           {"keywords":["neptune"],"labels":["@aws-cdk/aws-neptune"],"assignees":["nija-at"]},
           {"keywords":["opsworks","ops works"],"labels":["@aws-cdk/aws-opsworks"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["opsworkscm"],"labels":["@aws-cdk/aws-opsworkscm"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["personalize"],"labels":["@aws-cdk/aws-personalize"],"assignees":["NetaNir"]},
           {"keywords":["pinpoint"],"labels":["@aws-cdk/aws-pinpoint"],"assignees":["iliapolo"]},
           {"keywords":["pinpointemail","pinpoint email"],"labels":["@aws-cdk/aws-pinpointemail"],"assignees":["iliapolo"]},
           {"keywords":["qldb"],"labels":["@aws-cdk/aws-qldb"],"assignees":["shivlaks"]},
           {"keywords":["ram"],"labels":["@aws-cdk/aws-ram"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["rds"],"labels":["@aws-cdk/aws-rds"],"assignees":["nija-at"]},
           {"keywords":["redshift","red shift"],"labels":["@aws-cdk/aws-redshift"],"assignees":["nija-at"]},
           {"keywords":["robomaker"],"labels":["@aws-cdk/aws-robomaker"],"assignees":["NetaNir"]},
           {"keywords":["route53","route 53"],"labels":["@aws-cdk/aws-route53"],"assignees":["shivlaks"]},
           {"keywords":["route53-patterns","route53 patterns"],"labels":["@aws-cdk/aws-route53-patterns"],"assignees":["shivlaks"]},
           {"keywords":["route53-targets","route53 targets"],"labels":["@aws-cdk/aws-route53-targets"],"assignees":["shivlaks"]},
           {"keywords":["route53resolver","route53 resolver"],"labels":["@aws-cdk/aws-route53resolver"],"assignees":["shivlaks"]},
           {"keywords":["s3"],"labels":["@aws-cdk/aws-s3"],"assignees":["iliapolo"]},
           {"keywords":["s3-assets","s3 assets"],"labels":["@aws-cdk/aws-s3-assets"],"assignees":["iliapolo"]},
           {"keywords":["s3-deployment","s3 deployment"],"labels":["@aws-cdk/aws-s3-deployment"],"assignees":["iliapolo"]},
           {"keywords":["s3-notifications","s3 notifications"],"labels":["@aws-cdk/aws-s3-notifications"],"assignees":["iliapolo"]},
           {"keywords":["sagemaker"],"labels":["@aws-cdk/aws-sagemaker"],"assignees":["NetaNir"]},
           {"keywords":["sam"],"labels":["@aws-cdk/aws-sam"],"assignees":["nija-at"]},
           {"keywords":["sdb"],"labels":["@aws-cdk/aws-sdb"],"assignees":["nija-at"]},
           {"keywords":["secretsmanager","secrets manager"],"labels":["@aws-cdk/aws-secretsmanager"],"assignees":["skinny85"]},
           {"keywords":["securityhub","security hub"],"labels":["@aws-cdk/aws-securityhub"],"assignees":["rix0rrr"]},
           {"keywords":["servicecatalog","service catalog"],"labels":["@aws-cdk/aws-servicecatalog"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["servicediscovery","service discovery"],"labels":["@aws-cdk/aws-servicediscovery"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["ses"],"labels":["@aws-cdk/aws-ses"],"assignees":["iliapolo"]},
           {"keywords":["ses-actions","ses actions"],"labels":["@aws-cdk/aws-ses-actions"],"assignees":["iliapolo"]},
           {"keywords":["sns"],"labels":["@aws-cdk/aws-sns"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["sns-subscriptions","sns subscriptions"],"labels":["@aws-cdk/aws-sns-subscriptions"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["sqs"],"labels":["@aws-cdk/aws-sqs"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["ssm"],"labels":["@aws-cdk/aws-ssm"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["stepfunctions","step functions"],"labels":["@aws-cdk/aws-stepfunctions"],"assignees":["shivlaks"]},
           {"keywords":["stepfunctions-tasks","stepfunctions tasks"],"labels":["@aws-cdk/aws-stepfunctions-tasks"],"assignees":["shiv"]},
           {"keywords":["aws-transfer"],"labels":["@aws-cdk/aws-transfer"],"assignees":["iliapolo"]},
           {"keywords":["waf"],"labels":["@aws-cdk/aws-waf"],"assignees":["rix0rrr"]},
           {"keywords":["wafregional","waf regional"],"labels":["@aws-cdk/aws-wafregional"],"assignees":["rix0rrr"]},
           {"keywords":["wafv2","waf v2"],"labels":["@aws-cdk/aws-wafv2"],"assignees":["rix0rrr"]},
           {"keywords":["workspaces"],"labels":["@aws-cdk/aws-workspaces"],"assignees":["NetaNir"]},
           {"keywords":["cfnspec","cfn spec"],"labels":["@aws-cdk/cfnspec"],"assignees":["eladb"]},
           {"keywords":["cloudformation-diff","cloudformation diff"],"labels":["@aws-cdk/cloudformation-diff"],"assignees":["shivlaks"]},
           {"keywords":["core"],"labels":["@aws-cdk/core"],"assignees":["eladb"]},
           {"keywords":["custom-resources","custom resources"],"labels":["@aws-cdk/custom-resources"],"assignees":["eladb"]},
           {"keywords":["cx-api","cx api"],"labels":["@aws-cdk/cx-api"],"assignees":["eladb"]},
           {"keywords":["region-info","region info"],"labels":["@aws-cdk/region-info"],"assignees":["eladb"]},
           {"keywords":["@aws-cdk/aws-acmpca","aws-acmpca","acmpca"],"labels":["@aws-cdk/aws-acmpca"],"assignees":["skinny85"]},
           {"keywords":["@aws-cdk/aws-appconfig","aws-appconfig","app config","appconfig"],"labels":["@aws-cdk/aws-appconfig"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["@aws-cdk/aws-cassandra","aws-cassandra","cassandra"],"labels":["@aws-cdk/aws-cassandra"],"assignees":["iliapolo"]},
           {"keywords":["@aws-cdk/aws-ce","aws-ce"],"labels":["@aws-cdk/aws-ce"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["@aws-cdk/aws-chatbot","aws-chatbot","chatbot"],"labels":["@aws-cdk/aws-chatbot"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["@aws-cdk/aws-codeguruprofiler","aws-codeguruprofiler","code guru profiler","codeguruprofiler","codeguru profiler"],"labels":["@aws-cdk/aws-codeguruprofiler"],"assignees":["skinny85"]},
           {"keywords":["@aws-cdk/aws-detective","aws-detective","detective"],"labels":["@aws-cdk/aws-detective"],"assignees":["rix0rrr"]},
           {"keywords":["@aws-cdk/aws-eventschemas","aws-eventschemas","event schemas","eventschemas"],"labels":["@aws-cdk/aws-eventschemas"],"assignees":["rix0rrr"]},
           {"keywords":["@aws-cdk/aws-fms","aws-fms","fms"],"labels":["@aws-cdk/aws-fms"],"assignees":["rix0rrr"]},
           {"keywords":["@aws-cdk/aws-globalaccelerator","aws-globalaccelerator","global accelerator","globalaccelerator"],"labels":["@aws-cdk/aws-globalaccelerator"],"assignees":["rix0rrr"]},
           {"keywords":["@aws-cdk/aws-imagebuilder","aws-imagebuilder","image builder","imagebuilder"],"labels":["@aws-cdk/aws-imagebuilder"],"assignees":["rix0rrr"]},
           {"keywords":["@aws-cdk/aws-networkmanager","aws-networkmanager","network manager","networkmanager"],"labels":["@aws-cdk/aws-networkmanager"],"assignees":["rix0rrr"]},
           {"keywords":["@aws-cdk/aws-resourcegroups","aws-resourcegroups","resource groups","resourcegroups"],"labels":["@aws-cdk/aws-resourcegroups"],"assignees":["MrArnoldPalmer"]},
           {"keywords":["@aws-cdk/aws-synthetics","aws-synthetics","synthetics"],"labels":["@aws-cdk/aws-synthetics"],"assignees":["rix0rrr"]},
           {"keywords":["@aws-cdk/aws-apigatewayv2","aws-apigatewayv2","apigateway v2","apigatewayv2"],"labels":["@aws-cdk/aws-apigatewayv2"],"assignees":["nija-at"]},
           {"keywords":["@aws-cdk/aws-lambda-nodejs","aws-lambda-nodejs","lambda-nodejs","lambda nodejs"],"labels":["@aws-cdk/aws-lambda-nodejs"],"assignees":["eladb"]},
           {"keywords":["@aws-cdk/cloudformation-include","cloudformation-include","cloudformation-include","cloudformation include"],"labels":["@aws-cdk/cloudformation-include"],"assignees":["skinny85"]},
           {"keywords":["@aws-cdk/cloud-assembly-schema","cloud-assembly-schema","cloud-assembly-schema","cloud assembly schema"],"labels":["@aws-cdk/cloud-assembly-schema"],"assignees":["eladb"]}
           ]

