name: PR Build

on:
  pull_request:
    branches:
      - main
      - v2-release

jobs:
  build:
    runs-on:
      - ubuntu-latest

    env:
      PR_BUILD: true

    steps:
      - name: Checkout code1
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"        

      - name: Build
        run: /bin/bash ./build.sh --ci          
