name: PR Build

on:
  workflow_dispatch: {}
  merge_group: {}
  push:
    branches:
      - main
      - v2-release
  pull_request:
    branches:
      - main
      - v2-release

# For every PR, cancel any previous builds in progress
# ... but for all other builds we keep them running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: aws-cdk_ubuntu-latest_32-core

    env:
      PR_BUILD: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "yarn"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.s3buildcache
          key: ${{ runner.os }}-${{ github.event.pull_request.base.ref }}-s3buildcache

      - name: Configure system settings
        run: |
          (command -v sysctl || sudo apt-get update && sudo apt-get install -y procps) && \
          sudo sysctl -w vm.max_map_count=2251954

      - name: Build
        run: /bin/bash ./build.sh --ci

      - name: Run Rosetta
        run: /bin/bash ./scripts/run-rosetta.sh

      - name: Check for uncommitted changes
        run: git diff-index --exit-code --ignore-space-at-eol --stat HEAD
