name: pr-linter-exemption-labeler
on:
  issue_comment:
    types:
      - created
      - edited
      - deleted

jobs:
  pr_commented:
    name: PR Comment
    if: ${{ (github.event.issue.pull_request) && (github.event.issue.state == 'open') }}
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    environment: automation
    steps:
      - uses: cdklabs/pr-linter-exemption-labeler@9ad6c8b06f6a92a49b8529c8e493e0b1b6ba7111 # main
        with:
          github-token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
