name: P1 Bug Prioritization
on:
  issues:
    types:
      - labeled

permissions:
  contents: read

jobs:
  prioritize:
    if: github.repository == 'aws/aws-cdk' && contains(github.event.issue.labels.*.name, 'bug') && contains(github.event.issue.labels.*.name, 'p1')
    runs-on: ubuntu-latest
    environment: automation
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - name: Add P1 Bug to project
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        with:
          github-token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/prioritization/assign-bug-priority.js')
            await script({github, context})
