name: PR Prioritization
on:
  pull_request_target:
    types:
      - labeled
      - opened
      - reopened
      - synchronize
      - ready_for_review

permissions:
  contents: read

jobs:
  prioritize:
    if: github.repository == 'aws/aws-cdk'
    runs-on: ubuntu-latest
    environment: automation
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Add PR to Project & Set Priority
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          github-token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          script: |
            const script = require('./scripts/prioritization/assign-priority.js')
            await script({github, context})
