# Request a deployment to the test pipeline

name: request-cli-integ-test
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

permissions:
  contents: read

jobs:
  cli-changes:
    runs-on: ubuntu-latest
    outputs:
      any-changed-files: ${{ steps.changed-cli-files.outputs.cli_any_changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0
          persist-credentials: false
      - name: Find changed cli files
        id: changed-cli-files
        uses: step-security/changed-files@2e07db73e5ccdb319b9a6c7766bd46d39d304bad
        with:
          base_sha: ${{ github.event.pull_request.base.sha }}
          files_yaml: |
            cli:
              - packages/aws-cdk-lib/cx-api/lib/features.ts
  approve-test-pipeline:
    needs: cli-changes
    if: needs.cli-changes.outputs.any-changed-files == 'true' || contains(github.event.pull_request.labels.*.name, 'pr/request-cli-integ-tests')
    environment: test-pipeline
    runs-on: ubuntu-latest
    steps:
      - run: echo "Approved"
  submit-to-test-pipeline:
    needs:
      - approve-test-pipeline
      - cli-changes
    runs-on: ubuntu-latest
    environment: automation
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Needs to run with PROJEN_GITHUB_TOKEN because we need permissions to force push the branch
          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: Submit to test-pipeline
        run: |
          git config --global user.name 'aws-cdk-automation'
          git config --global user.email 'aws-cdk-automation@users.noreply.github.com'
          git push --force --atomic https://github.com/${{ github.repository }}.git FETCH_HEAD:test-main-pipeline
