name: "Assigns members from team aws-cdk-owners to PRs"
on:
 pull_request_target:
    types: [opened]

jobs:
  team-assignment-manager:
    runs-on: ubuntu-latest
    steps:
      - uses: peterwoodworth/team-assignment-manager@main
        with:
          github-token: "${{ secrets.PROJEN_GITHUB_TOKEN }}"
          team: "aws-cdk-owners"
          exempt-team: "aws-cdk-team"

