/* eslint-disable import/no-extraneous-dependencies */
export { DEFAULT_TOOLKIT_STACK_NAME, SdkProvider } from 'aws-cdk/lib';
export type { SuccessfulDeployStackResult } from 'aws-cdk/lib';
export { formatSdkLoggerContent } from 'aws-cdk/lib/api/aws-auth/sdk-logger';
export { CloudAssembly, sanitizePatterns, StackCollection, ExtendedStackSelection } from 'aws-cdk/lib/api/cxapp/cloud-assembly';
export { prepareDefaultEnvironment, prepareContext, spaceAvailableForContext } from 'aws-cdk/lib/api/cxapp/exec';
export { Deployments } from 'aws-cdk/lib/api/deployments';
export { HotswapMode } from 'aws-cdk/lib/api/hotswap/common';
export { StackActivityProgress } from 'aws-cdk/lib/api/util/cloudformation/stack-activity-monitor';
export { RWLock } from 'aws-cdk/lib/api/util/rwlock';
export type { ILock } from 'aws-cdk/lib/api/util/rwlock';
export { formatTime } from 'aws-cdk/lib/api/util/string-manipulation';
export * as contextproviders from 'aws-cdk/lib/context-providers';
export { ResourceMigrator } from 'aws-cdk/lib/migrator';
export { obscureTemplate, serializeStructure } from 'aws-cdk/lib/serialize';
export { Context, Settings, PROJECT_CONTEXT } from 'aws-cdk/lib/settings';
export { tagsForStack } from 'aws-cdk/lib/tags';
export { CliIoHost } from 'aws-cdk/lib/toolkit/cli-io-host';
export { loadTree, some } from 'aws-cdk/lib/tree';
export { splitBySize } from 'aws-cdk/lib/util';
export { validateSnsTopicArn } from 'aws-cdk/lib/util/validate-notification-arn';
export { WorkGraph } from 'aws-cdk/lib/util/work-graph';
export type { Concurrency } from 'aws-cdk/lib/util/work-graph';
export { WorkGraphBuilder } from 'aws-cdk/lib/util/work-graph-builder';
export type { AssetBuildNode, AssetPublishNode, StackNode } from 'aws-cdk/lib/util/work-graph-types';
export { versionNumber } from 'aws-cdk/lib/version';
export { guessExecutable } from 'aws-cdk/lib/api/cxapp/exec';
